# yaml 配置
version: "3.7"
services:
  mysql8019:
    image: "mysql:8.0.19"
    ports:
      - "3306:3306"
    command: "--default-authentication-plugin=mysql_native_password --init-file /data/application/init.sql"
    environment:
      MYSQL_ROOT_PASSWORD: "root123123"
      MYSQL_DATABASE: "gin_web_demo"
      MYSQL_PASSWORD: "root123123"
    volumes:
      - ./init.sql:/data/application/init.sql
  redis507:
    image: "redis:5.0.7"
    command: redis-server --requirepass 123
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
  gin_web_demo:
    build: .
    command: sh -c "./wait-for.sh mysql8019:3306 redis507:6379 -- ./gin_web_demo ./conf/config.yaml"
    depends_on:
      - mysql8019
      - redis507
    ports:
      - "8888:8084"